version: '3'

services:

  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
 
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "8081:8888"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888"]
      interval: 10s
      timeout: 10s
      retries: 3

  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
       - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  postgres:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - env_file.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    
volumes:
  redis-data:
  db-data: