version: '3'

services:

  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
 
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "8081:8888"
    depends_on:
      - postgres

  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
       - redis-data:/data

  postgres:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    
volumes:
  redis-data:
  db-data: